print('*** RUNNING ALL TESTS ***');

include 'aliases.es';
:SetLogLevel(DEBUG);
include 'plus.es';
include 'minus.es';
include 'mult.es';
include 'div.es';
include 'exp.es';
include 'eq.es';
include 'lte.es';
include 'gte.es';
include 'lt.es';
include 'gt.es';
include 'ne.es';
include 'cond.es';
include 'average.es';
include 'stdev.es';
include 'put.es';
include 'null.es';
include 'collapse.es';
include 'T1.es';
include 'T2.es';
include 'T3.es';
include 'T4.es';
include 'returns.es';
include 'strings.es';
include 'trycatch.es';
include 'const.es';

print("*** TESTS COMPLETED SUCCESSFULLY ***");
